### ISSUE TITLE
Perplexity timeout?

### ISSUE THREAD

**Issue by EGMSSE** [EricZinda/InductorSoftwareBlogComments#2] opened 2023-11-04 13:21 UTC
Hi, tried playing perplexity and after every input attempt I receive something along the lines of:

`{errorMessage=2023-11-04T13:16:32.757Z 9af64329-9d42-41d8-b451-08584c030d81 Task timed out after 20.02 seconds}`

 Curious if you're still maintaining the game or not. Thanks!

**Comment by EricZinda** [comment] 2023-11-06 19:39
Thanks for reporting @EGMSSE !  I am absolutely maintaining it, but somehow my notifications for issues quit being delivered so I didn't notice it was down.  Looking at it now...

**Comment by EricZinda** [comment] 2023-11-06 20:51
OK, fixed now!  Thanks again for reporting!

**Closed as completed by EricZinda** 2023-11-06 20:51 UTC

**Comment by EGMSSE** [comment] 2023-11-11 18:02
Just tried it and still seem to be getting the error message

'errorMessage=2023-11-11T18:01:05.310Z 4bc2ecab-0577-4699-bf63-992b1f83cae8 Task timed out after 20.02 seconds'

**Comment by EricZinda** [comment] 2023-11-14 18:00
Ugh! I should have tested my "website down" test better.  Thanks for keeping at this!  It should be up again now, and I should get better notifications if it stops responding.  There is a subtle bug somewhere in the server that is causing it to need to be rebooted that I'm still tracking down that is the root cause.  But, at least now I know when to reboot!
